# Rol 1: Diseñador de Datos - Modelado y Generación 
**Objetivo:** Diseñar la estructura de datos sintéticos base para el análisis del incidente SolarWinds

**Librerias Uilizadas**

In [10]:
import pandas as pd
import numpy as np
from faker import Faker
import random
import os
from datetime import timedelta

Fijamos `seed = 42` en `numpy`, `random` y `Faker` para cumplir con el requisito académico. Así, cada ejecución genera exactamente los mismos datos, facilitando la validación y la sustentación.

In [11]:


# Semilla para que los datos salgan iguales cada vez
seed = 42

np.random.seed(seed)
random.seed(seed)
Faker.seed(seed) 

# Faker para generar nombres de organizaciones realistas pero ficticios
fake = Faker()

# Carpeta donde se guardan los csv
RUTA_DATA = 'data'
os.makedirs(RUTA_DATA, exist_ok=True)  # Si la carpeta no existe, la crea

**Generación de tabla clientes** Se generó una tabla con 50 registros, los datos se generaron de forma aleatoria pero manteniendo la coherencia con el contexto del caso.

In [12]:
# Generar tabla clientes
def generar_clientes(n=50):

    sectores = [
        'Tecnología',
        'Ciberseguridad',
        'Gobierno',
        'Finanzas',
        'Operaciones de red'
    ]

    paises = [
        'Estados Unidos',
        'México',
        'Costa Rica',
        'Perú',
        'Colombia'
    ]

    clientes = []

    for i in range(1, n + 1):

        clientes.append({
            'cliente_id': i,
            'nombre_organizacion': fake.company(),
            'tipo_org': random.choice([
                'Pública',
                'Privada',
                'Académica'
            ]),

            'pais': random.choice(paises),
            'sector': random.choice(sectores),
            'criticidad': random.choice([
                'Alta',
                'Media',
                'Baja'
            ])
        })

    
    clientes_df = pd.DataFrame(clientes)

    # Exportar a CSV
    clientes_df.to_csv(
        os.path.join(RUTA_DATA, 'clientes.csv'),
        index=False
    )
    print("clientes.csv generado")
    return clientes_df

**Vizualización de clientes**

In [13]:
# Ejecutamos la función
clientes_df = generar_clientes(50)
clientes_df.head()

clientes.csv generado

,cliente_id,nombre_organizacion,tipo_org,pais,sector,criticidad
0,1,"Rodriguez, Figueroa and Sanchez",Académica,Estados Unidos,Tecnología,Baja
1,2,Doyle Ltd,Privada,México,Ciberseguridad,Alta
2,3,"Mcclain, Miller and Henderson",Académica,Estados Unidos,Operaciones de red,Alta
3,4,Davis and Sons,Académica,Perú,Tecnología,Alta
4,5,"Guzman, Hoffman and Baldwin",Pública,México,Ciberseguridad,Baja

**Generación tabla versiones** Esta tabla contiene los 8 lanzamientos de Orion que se mencionan en el caso de estudio entre 2019 y 2021. Cada registro incluye el identificador de la versión, su nombre, la fecha en que fue publicada y la fecha de compilación del malware. El campo clave es `contiene_sunburst`, que indica si esa versión específica fue comprometida con el backdoor.

In [14]:
# Generar tabla versiones
def generar_versiones():

    versiones = [
        {'version_id': 101, 'nombre_version': 'Orion 2019.4', 'fecha_release': '2019-06-15', 'contiene_sunburst': True, 'fecha_compilacion': '2020-02-20'},
        {'version_id': 102, 'nombre_version': 'Orion 2019.4 HF1', 'fecha_release': '2019-09-10', 'contiene_sunburst': True, 'fecha_compilacion': '2020-02-20'},
        {'version_id': 103, 'nombre_version': 'Orion 2019.4 HF2', 'fecha_release': '2019-12-01', 'contiene_sunburst': True, 'fecha_compilacion': '2020-02-20'},
        {'version_id': 104, 'nombre_version': 'Orion 2019.4 HF5', 'fecha_release': '2020-03-26', 'contiene_sunburst': False, 'fecha_compilacion': '2020-03-20'},
        {'version_id': 105, 'nombre_version': 'Orion 2020.2', 'fecha_release': '2020-05-10', 'contiene_sunburst': True, 'fecha_compilacion': '2020-02-20'},
        {'version_id': 106, 'nombre_version': 'Orion 2020.2 HF1', 'fecha_release': '2020-08-15', 'contiene_sunburst': True, 'fecha_compilacion': '2020-02-20'},
        {'version_id': 107, 'nombre_version': 'Orion 2020.2.1', 'fecha_release': '2020-10-10', 'contiene_sunburst': False, 'fecha_compilacion': '2020-10-01'},
        {'version_id': 108, 'nombre_version': 'Orion 2021.1', 'fecha_release': '2021-01-15', 'contiene_sunburst': False, 'fecha_compilacion': '2021-01-05'}
    ]

    versiones_df = pd.DataFrame(versiones)
    versiones_df['fecha_release'] = pd.to_datetime(versiones_df['fecha_release'])
    versiones_df['fecha_compilacion'] = pd.to_datetime(versiones_df['fecha_compilacion'])
    
    versiones_df.to_csv(
        os.path.join(RUTA_DATA, 'versiones_software.csv'),
        index=False
    )
    print("versiones_software.csv generado")
    return versiones_df

**Vizualización de versiones**

In [15]:
# Ejecutamos la función
versiones_df = generar_versiones()
versiones_df

versiones_software.csv generado

,version_id,nombre_version,fecha_release,contiene_sunburst,fecha_compilacion
0,101,Orion 2019.4,2019-06-15,True,2020-02-20
1,102,Orion 2019.4 HF1,2019-09-10,True,2020-02-20
2,103,Orion 2019.4 HF2,2019-12-01,True,2020-02-20
3,104,Orion 2019.4 HF5,2020-03-26,False,2020-03-20
4,105,Orion 2020.2,2020-05-10,True,2020-02-20
5,106,Orion 2020.2 HF1,2020-08-15,True,2020-02-20
6,107,Orion 2020.2.1,2020-10-10,False,2020-10-01
7,108,Orion 2021.1,2021-01-15,False,2021-01-05

**Generación tabla instalaciones**
Se creó una tabla de 100 registros,vinculando cada cliente con una versión específica de Orion. Para mantener coherencia entre las fechas de instalación se calcularon sumando entre 15 y 300 días a la fecha de lanzamiento `fecha_release` de cada versión, que es el tiempo real que tardan las organizaciones en implementar software, evitando registrar instalaciones antes de que la versión existiera.

Se incluyó el campo `nivel_datos_sensibles` para representar la criticidad de la información manejada en cada entorno, evaluando la calidad de los datos e identificando qué instalaciones estuvieron realmente expuestas al malware SUNBURST.

In [19]:
# Generar tabla instalaciones
def generar_instalaciones(clientes_df, versiones_df, n=100):

    instalaciones = []
    for i in range(1, n + 1):
        cliente_id = int(
            np.random.choice(clientes_df['cliente_id'])
        )
        version_id = int(
            np.random.choice(versiones_df['version_id'])
        )

        # Buscar fecha release de la versión
        fecha_release = versiones_df.loc[
            versiones_df['version_id'] == version_id,
            'fecha_release'
        ].values[0]    # Extraer el valor único de la fecha para poder hacer la suma de días

        dias_despues = np.random.randint(15, 300)
        fecha_instalacion = (
            fecha_release + timedelta(days=int(dias_despues)) # Días después de la salida de la versión
        )

        instalaciones.append({

            'instalacion_id': i,
            'cliente_id': cliente_id,
            'version_id': version_id,
            'fecha_instalacion': fecha_instalacion,
           'nivel_datos_sensibles': random.randint(1, 5)
        })


    # Convertir a DataFrame
    instalaciones_df = pd.DataFrame(instalaciones)

    #Cambiar las fechas a formato datetime para poder filtrar, comparar y ordenar 
    instalaciones_df['fecha_instalacion'] = pd.to_datetime( instalaciones_df['fecha_instalacion'])

    # Exportar a CSV
    instalaciones_df.to_csv(
        os.path.join(RUTA_DATA, 'instalaciones.csv'),
        index=False
    )
    print("instalaciones.csv generado")
    return instalaciones_df

**Vizualización de instalaciones**

In [18]:
# Ejecutamos la función
instalaciones_df = generar_instalaciones(clientes_df, versiones_df, 100)
instalaciones_df.head()

instalaciones.csv generado

,instalacion_id,cliente_id,version_id,fecha_instalacion,nivel_datos_sensibles
0,1,35,108,2021-07-17,5
1,2,36,101,2019-09-05,5
2,3,33,106,2021-06-02,1
3,4,48,104,2020-08-22,3
4,5,3,101,2019-11-04,1

**Generar diccionario**

In [ ]:
def generar_diccionario(clientes_df, versiones_df, instalaciones_df):

    os.makedirs('docs', exist_ok=True)
    
    tablas = [
        ('CLIENTES', clientes_df), 
        ('VERSIONES_SOFTWARE', versiones_df), 
        ('INSTALACIONES', instalaciones_df)
    ]
    
    with open('docs/Diccionario_de_Datos.txt', 'w', encoding='utf-8') as f:
        for nombre, df in tablas:
            print(f"TABLA: {nombre} ({len(df)} registros)", file=f)
            
            for col in df.columns:
                # Extrae directamente el tipo de dato original de Pandas (int64, object, etc.)
                tipo = df[col].dtype
                
                # Lo escribe directamente en el archivo
                print(f"  • {col}: {tipo}", file=f)

**Validación de integridad y relaciones**  
 Este codigo comprueba que todos los `cliente_id` y `version_id` registrados en la tabla de instalaciones existan realmente en las tablas de clientes y versiones.

`.isin()` compara cada valor de la tabla hija contra la lista de IDs en las tablas padre, devolviendo `True` si existe y `False` si no. La función `.all()` asegura que  los registros cumplan esta condición. Si alguna validación falla, significa que hay registros no existentes, generando errores.

Teniendo en cuenta los principios de calidad del DAMA DMBOK en cuanto a gestión de datos, esto garantiza que los datos sintéticos que se han generado sean coherentes y se utilicen de forma correcta para el análisis del caso SUNBURST.

In [ ]:

print(" Validando relaciones")

#Verificar que los ids existan en las otras tablas
clientes_validos = instalaciones_df['cliente_id'].isin(  
    clientes_df['cliente_id']
).all()  #.all() verifica que todos los valores sean True, si fallan da False

#Comprueba que cada versión instalada realmente exista en la tabla padre.
versiones_validas = instalaciones_df['version_id'].isin(
    versiones_df['version_id']
).all()

if clientes_validos and versiones_validas:
    print("Integridad correcta")
else:
    print(" Error en relaciones")

 Validando relaciones
Integridad correcta

**Ejecución de datos**

In [ ]:
print("\nCLIENTES")
    print(clientes_df.head())

    print("\nVERSIONES")
    print(versiones_df.head())

    print("\nINSTALACIONES")
    print(instalaciones_df.head())

    print("\nDatos generados")

    generar_diccionario(clientes_df, versiones_df, instalaciones_df)
    print("Diccionario generado")

**Conclusión**
Se revisó de que las tablas estuvieran bien conectadas entre sí, que las fechas tuvieran lógica debido a que no se puede instalar un software antes de que salga y que cada vez que corramos el código nos dé los mismos resultados. 

Se exporto los archivos CSV  ubicados en lal carpeta data Y por ultimo se verificó la integridad entre tablas asegurando que todo este conectado en el modelo de datos propuestos por DAMA DMBOK, especialmente en aspectos de integridad y gestión de datos relacionales.